topoguide/itineraires/urls.py
from django.urls import path

from . import views

app_name = 'itineraires'

urlpatterns = [
    path('', views.itineraires, name='itineraires'),
    path('sorties/<int:itineraire_id>/', views.sorties, name='sorties'),
    path('sortie/<int:sortie_id>/', views.sortie, name='sortie'),
    path('nouvelle_sortie/', views.nouvelle_sortie, name='nouvelle_sortie'),
    path('modif_sortie/<int:sortie_id>/', views.modif_sortie, name='modif_sortie'),
]

topoguide/topoguide/urls.py
from django.contrib import admin
from django.urls import include, path

from itineraires import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    
    path('itineraires/', include('itineraires.urls')),
    path('', views.itineraires, name='itineraires'),
]

    

topoguide/itineraires/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import User
from django.conf import settings



class Itineraire(models.Model):
    titre = models.CharField(max_length=200)
    pointDepart = models.CharField(max_length=100)
    description = models.CharField(max_length=350)
    altitudeDepart = models.FloatField('Altitude de depart (m)')
    altitudeMin = models.FloatField('Altitude minimale (m)')
    altitudeMax = models.FloatField('Altitude maximale (m)')
    denivPosCum = models.FloatField('Dénivelé Positif Cumulé (m)')
    denivNegCum = models.FloatField('Dénivelé Negatif Cumulé (m)')
    duree = models.TimeField()
    difficulte = models.IntegerField(validators=[MinValueValidator(limit_value=1), MaxValueValidator(limit_value=5)])
    

class Sortie(models.Model):
    utilisateur = models.ForeignKey(User, on_delete=models.CASCADE)
    itineraire = models.ForeignKey('Itineraire', on_delete=models.CASCADE)
    
    date = models.DateField()
    duree = models.TimeField()
    nombrePersonnes = models.IntegerField("Nombre de personnes")
    
    DEBUTANTS = 'DEB'
    EXPERIMENTES = 'EXP'
    MIXTES = 'MIX'
    
    EXP_CHOICES = [
        (DEBUTANTS, 'Debutants'),
        (EXPERIMENTES, 'Experimentes'),
        (MIXTES, 'Mixtes'),
    ]
    
    experience = models.CharField(max_length=30, choices=EXP_CHOICES)
    
    BONNE = 'BON'
    MOYENNE = 'MOY'
    MAUVAISE = 'MAL'
    
    METEO_CHOICES = [
        (BONNE, 'Bonne'),
        (MOYENNE, 'Moyenne'),
        (MAUVAISE, 'Mauvaise'),
    ]    
    
    meteo = models.CharField(max_length=20, choices=METEO_CHOICES)
    
    difficulte = models.IntegerField(validators=[MinValueValidator(limit_value=1), MaxValueValidator(limit_value=5)])
    

topoguide/itineraires/forms.py
from django import forms

from .models import Sortie

class SortieForm(forms.ModelForm):
    class Meta:
        model = Sortie
        fields = '__all__' 

topoguide/itineraires/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_list_or_404, get_object_or_404, render, redirect
from django.http import Http404

from .models import Itineraire, Sortie
from .forms import SortieForm



@login_required() 
def itineraires(request):
    itineraires = get_list_or_404(Itineraire)
    return render(request, 'itineraires/itineraires.html', {'itineraires': itineraires})

@login_required() 
def sorties(request, itineraire_id):
    sorties = get_list_or_404(Sortie, itineraire=itineraire_id)
    return render(request, 'itineraires/sorties.html', {'sorties': sorties})


@login_required() 
def sortie(request, sortie_id):
    sortie = get_object_or_404(Sortie, pk=sortie_id)
    return render(request, 'itineraires/sortie.html', {'sortie': sortie})

@login_required() 
def nouvelle_sortie(request):
    if request.method == 'GET':
        form = SortieForm()
    elif request.method == 'POST':
        form = SortieForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('itineraires:itineraires')
    return render(request, 'itineraires/nouvelle_sortie.html', {'form': form})


@login_required() 
def modif_sortie(request, sortie_id):
    # il faut ajouter restriction d'utilisateur
    sortie = Sortie.objects.get(pk=sortie_id)
    if request.method == 'GET':
        form = SortieForm(instance=sortie)
    elif request.method == 'POST':
        form = SortieForm(request.POST, instance=sortie)
        if form.is_valid():
            form.save()
            return redirect('itineraires:itineraires')
    return render(request, 'itineraires/modif_sortie.html', {'form': form})
    

topoguide/templates/base.html
{% load static %}
{% load bootstrap5 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {# Load CSS and JavaScript #}
    {% bootstrap_css %}
    {% bootstrap_javascript %}

    {# Display django.contrib.messages as Bootstrap alerts #}
    {% bootstrap_messages %}
    <title>{% block title %}Topoguide{% endblock %}</title>
</head>

<body>
    <div class="container">
        <div class="row pb-3">
            <header>
                Topoguide Assignment with SQLite<br>
                <img src="{% static 'images/topoguide.jpeg' %}" width=150px alt="logo"/>
            </header>
        </div>

        {% block content %}{% endblock %}

        <div class="row pt-5">
            <footer>
                <em>&copy; ISAE-SUPAERO</em>
            </footer>
        </div>
    </div>
</body>
</html>

topoguide/templates/itineraires/itineraires.html
{% extends 'base.html' %}
{% load bootstrap5 %} 

{% block title %}Itineraires List{% endblock title%}

{% block content %}

{% comment %} Titre {% endcomment %}
    <div class="row pb-3">
        <h1>Itineraires</h1>
    </div>

{% comment %} Table d'itinéraires avec détails {% endcomment %}
    <div class="row">
        {% if itineraires %}
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>Itineraires</th>
                    <th>Point de départ</th>
                    <th>Description</th>
                    <th>Alt Depart</th>
                    <th>Alt Min </th>
                    <th>Alt Max </th>
                    <th>Deniv Pos Cum</th>
                    <th>Deniv Neg Cum</th>
                    <th>Durée estimée</th>
                    <th>Difficulté estimée</th>
                </tr>
                </thead>
                <tbody>
                {% for itineraire in itineraires %}
                    <tr>
                        <td><a href="{% url 'itineraires:sorties' itineraire.id %}"><h>Itineraire </h>{{ itineraire.id }}</a></td>
                        <td>{{ itineraire.pointDepart }}</td>
                        <td>{{ itineraire.description }}</td>
                        <td>{{ itineraire.altitudeDepart }}</td>
                        <td>{{ itineraire.altitudeMin }}</td>
                        <td>{{ itineraire.altitudeMax }}</td>
                        <td>{{ itineraire.denivPosCum }}</td>
                        <td>{{ itineraire.denivNegCum }}</td>
                        <td>{{ itineraire.duree }}</td>
                        <td>{{ itineraire.difficulte }}</td>                   
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% else %}
            <div class="jumbotron"><i>No itineraire available.</i></div>
        {% endif %}
        </div>


{% comment %} Bouton {% endcomment %}
    <div class="row pt-3">
        <a class="btn btn-primary" href="{% url 'logout' %}">Déconnexion</a>
    </div>


{% endblock content %}

topoguide/templates/itineraires/modif_sortie.html
{% extends 'base.html' %}
{% load bootstrap5 %} 

{% block title %}Create New Sortie{% endblock title%}

{% block content %}


{% comment %} Modification de sortie {% endcomment %}
<form action="{% url 'itineraires:modif_sortie' form.instance.id %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button type="submit" class="btn btn-primary" >Update</button>
      <a href="{% url 'itineraires:itineraires' %}" class="btn btn-primary">Cancel</a>
    {% endbuttons %}
</form>

{% endblock content %}

topoguide/templates/itineraires/nouvelle_sortie.html
{% extends 'base.html' %}
{% load bootstrap5 %} 

{% block title %}Create New Sortie{% endblock title%}

{% block content %}


{% comment %} Creation de sortie {% endcomment %}
<form action="{% url 'itineraires:nouvelle_sortie' %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button type="submit" class="btn btn-primary">Add</button>
      <a href="{% url 'itineraires:sorties' %}" class="btn btn-primary">Cancel</a>
    {% endbuttons %}
</form>



{% comment %} Modification de sortie {% endcomment %}
<form action="{% url 'itineraires:modif_sortie' form.instance.id %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button type="submit" class="btn btn-primary">Update</button>
      <a href="{% url 'itineraires:sorties' %}" class="btn btn-primary">Cancel</a>
    {% endbuttons %}
</form>


{% endblock content %}

topoguide/templates/itineraires/sortie.html
{% extends 'base.html' %}
{% load bootstrap5 %} 

{% block title %}Sortie Details {{ sortie.id|truncatechars:10 }}' {% endblock title%}

{% block content %}

{% comment %} Titre {% endcomment %}
<div class="row pb-3">
    <h2>Sortie {{ sortie.id }} <small>by {{ sortie.utilisateur }}</small></h2>
</div>


{% comment %} Table de détails de la sortie{% endcomment %}
<div class="row">
    <table class="table table-striped">
        <thead>
        <tr>
            <th>Date</th>
            <th>Durée(h)</th>
            <th>Nombre de personnes</th>
            <th>Expérience du groupe</th>
            <th>Météo</th>
            <th>Difficulté</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ sortie.date }}</td>
                <td>{{ sortie.duree }}</td>
                <td>{{ sortie.nombrePersonnes }}</td>
                <td>{{ sortie.experience }}</td>
                <td>{{ sortie.meteo }}</td>
                <td>{{ sortie.difficulte }}</td>
            </tr>
        </tbody>
    </table>
</div>


{% comment %} Boutons  {% endcomment %}
<div class="row pt-3">
    <a class="btn btn-primary" href="{% url 'itineraires:sorties' sortie.itineraire.id %}">Back to Sorties list</a>
</div>

<div class="row pt-3">
    <a class="btn btn-primary" href="{% url 'logout' %}">Déconnexion</a>
</div>

{% endblock content %}

topoguide/templates/itineraires/sortie_details.html
{% extends 'base.html' %}

{% block title %}Sortie Details {{ sortie.id|truncatechars:10 }}' {% endblock title%}

{% block content %}

<div class="row pb-3">
    <h2>{{ sortie.id }} <small>by {{ sortie.utilisateur }}</small></h2>
</div>

<div class="row">
    <table class="table table-striped">
        <thead>
        <tr>
            <th>Date</th>
            <th>Durée(h)</th>
            <th>Météo</th>
            <th>Difficulté</th>
        </tr>
        </thead>
        <tbody>
        {% for sortie in sortie.all %}
            <tr>
                <td>{{ sortie.date }}</td>
                <td>{{ sortie.duree }}</td>
                <td>{{ sortie.meteo }}</td>
                <td>{{ sortie.difficulte }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

<div class="row pt-3">
    <a class="btn btn-primary" href="{% url 'itineraires:sortie_details' %}">Back to Sorties list</a>
</div>

{% endblock content %}

topoguide/templates/itineraires/sorties.html
{% extends 'base.html' %}
{% load bootstrap5 %} 

{% block title %}Sorties List{% endblock title%}

{% block content %}

{% comment %} Titre {% endcomment %}
    <div class="row pb-3">
        <h1>Sorties</h1>
    </div>

{% comment %} Table de sorties {% endcomment %}
    <div class="row">
        {% if sorties %}
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>Sorties</th>
                    <th>Utilisateur</th>
                    <th>Date</th>
                </tr>
                </thead>
                <tbody>
                {% for sortie in sorties %}
                    <tr>
                        <td><a href="{% url 'itineraires:sortie' sortie.id %}"><h>Sortie </h>{{ sortie.id }}</a></td>
                        <td>{{ sortie.utilisateur}}</td>
                        <td>{{ sortie.date}}</td>
                        <td><a href="{% url 'itineraires:modif_sortie' sortie.id %}"><h>Modifier la Sortie </h>{{ sortie.id }}</a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% else %}
            <div class="jumbotron"><i>No sortie available.</i></div>
        {% endif %}
        </div>

                
{% comment %} Boutons  {% endcomment %}
<div class="row pt-3">
    <a class="btn btn-primary" href="{% url 'itineraires:nouvelle_sortie' %}">Créer nouvelle Sortie</a>
</div>

<div class="row pt-3">
    <a class="btn btn-primary" href="{% url 'logout' %}">Déconnexion</a>
</div>
    

{% endblock content %}